// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/spotify/spotify.proto

package go_micro_srv_spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Spotify service

type SpotifyService interface {
	Play(ctx context.Context, in *PlayRequest, opts ...client.CallOption) (*PlayResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...client.CallOption) (*StopResponse, error)
}

type spotifyService struct {
	c    client.Client
	name string
}

func NewSpotifyService(name string, c client.Client) SpotifyService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.spotify"
	}
	return &spotifyService{
		c:    c,
		name: name,
	}
}

func (c *spotifyService) Play(ctx context.Context, in *PlayRequest, opts ...client.CallOption) (*PlayResponse, error) {
	req := c.c.NewRequest(c.name, "Spotify.Play", in)
	out := new(PlayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyService) Stop(ctx context.Context, in *StopRequest, opts ...client.CallOption) (*StopResponse, error) {
	req := c.c.NewRequest(c.name, "Spotify.Stop", in)
	out := new(StopResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spotify service

type SpotifyHandler interface {
	Play(context.Context, *PlayRequest, *PlayResponse) error
	Stop(context.Context, *StopRequest, *StopResponse) error
}

func RegisterSpotifyHandler(s server.Server, hdlr SpotifyHandler, opts ...server.HandlerOption) error {
	type spotify interface {
		Play(ctx context.Context, in *PlayRequest, out *PlayResponse) error
		Stop(ctx context.Context, in *StopRequest, out *StopResponse) error
	}
	type Spotify struct {
		spotify
	}
	h := &spotifyHandler{hdlr}
	return s.Handle(s.NewHandler(&Spotify{h}, opts...))
}

type spotifyHandler struct {
	SpotifyHandler
}

func (h *spotifyHandler) Play(ctx context.Context, in *PlayRequest, out *PlayResponse) error {
	return h.SpotifyHandler.Play(ctx, in, out)
}

func (h *spotifyHandler) Stop(ctx context.Context, in *StopRequest, out *StopResponse) error {
	return h.SpotifyHandler.Stop(ctx, in, out)
}
